# Server Configuration
server:
  port: 8082
  error:
    include-message: always

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG

spring:
  application:
    name: auth-service
  profiles:
    active: local