app:
  eureka:
    url: http://localhost:8081
  document:
    storage:
      path: ./document/storage
      max-file-size: 50MB

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082
          jwk-set-uri: http://localhost:8082/.well-known/jwks.json
  data:
    mongodb:
      authentication-database: admin
      username: mongodb
      password: mongodbpw
      database: dms
      port: 27017
      host: localhost
  rabbitmq:
    addresses: localhost:5672

# Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${app.eureka.url}/eureka
    enabled: true
  instance:
    preferIpAddress: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20