app:
  eureka:
    url: http://localhost:8081
  document:
    storage:
      path: ./document/storage
      max-file-size: 50MB

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082
          jwk-set-uri: http://localhost:8082/.well-known/jwks.json
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=dms
    username: postgres
    password: postgrespw
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    mongodb:
      authentication-database: admin
      username: mongodb
      password: mongodbpw
      database: dms
      port: 27017
      host: localhost
  rabbitmq:
    addresses: localhost:5672

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: ${app.eureka.url}/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
  instance:
    preferIpAddress: true
